#ifndef FAULT_SNAPSHOT_H
#define FAULT_SNAPSHOT_H

#define FAULT_BKP_REASON_REG BKP_DR11
#define FAULT_BKP_REASON_INV_REG BKP_DR12

#define FAULT_REASON_HARD ((UINT16)0x4846U)
#define FAULT_REASON_MEM ((UINT16)0x4D46U)
#define FAULT_REASON_BUS ((UINT16)0x4246U)
#define FAULT_REASON_USAGE ((UINT16)0x5546U)

#endif
