#ifndef PROJECT_STORAGE_FLASH_H
#define PROJECT_STORAGE_FLASH_H

#define FLASH_ADDR_IAP_START             0x08000000
#define FLASH_ADDR_APP_START             0x08004800

#if defined(STM32F10X_MD)
#define FLASH_STORAGE_PAGE_SIZE          ((UINT32)0x00000400)
#else
#define FLASH_STORAGE_PAGE_SIZE          ((UINT32)0x00000800)
#endif
#define FLASH_STORAGE_SLOT_SIZE          FLASH_STORAGE_PAGE_SIZE
#define FLASH_STORAGE_RECORD_ALIGNMENT   ((UINT16)2U)

/* Current persistent objects only. No legacy parameter migration areas. */
#define FLASH_ADDR_STORAGE_LOG_SLOT_A       ((UINT32)0x0801D000)
#define FLASH_ADDR_STORAGE_LOG_DELTA_A      ((UINT32)0x0801D400)
#define FLASH_ADDR_STORAGE_LOG_SLOT_B       ((UINT32)0x0801D800)
#define FLASH_ADDR_STORAGE_LOG_DELTA_B      ((UINT32)0x0801DC00)
#define FLASH_ADDR_STORAGE_SOC_SLOT_A       ((UINT32)0x0801E000)
#define FLASH_ADDR_STORAGE_CONFIG_SLOT_A    ((UINT32)0x0801E400)
#define FLASH_ADDR_STORAGE_SOC_SLOT_B       ((UINT32)0x0801E800)
#define FLASH_ADDR_STORAGE_CONFIG_SLOT_B    ((UINT32)0x0801EC00)

#define FLASH_STORAGE_AFE_WORD_COUNT     ((UINT16)24)
#define FLASH_STORAGE_RW_PARAM_PROTECT_WORD_COUNT   65
#define FLASH_STORAGE_RW_PARAM_OTHER_WORD_COUNT     32
#define FLASH_STORAGE_RW_PARAM_RESERVED_WORD_COUNT 24
#define FLASH_STORAGE_LOG_RECORD_COUNT   ((UINT16)100)
#define FLASH_STORAGE_SOC_DATA_VERSION_V3 ((UINT16)0x0003)
#define FLASH_STORAGE_SOC_DATA_VERSION_CURRENT FLASH_STORAGE_SOC_DATA_VERSION_V3
/* Source alias only. It maps to the current format and does not enable V2 loading. */
#define FLASH_STORAGE_SOC_DATA_VERSION_V2 FLASH_STORAGE_SOC_DATA_VERSION_CURRENT
#define FLASH_STORAGE_CONFIG_FORMAT_VERSION ((UINT16)0x0001)

#define FLASH_309_RTC_RTC_VALUE          ((UINT16)0x1222)
#define FLASH_309_RTC_NORMAL_VALUE       ((UINT16)0x2333)
#define FLASH_309_NORMAL_NORMAL_VALUE    ((UINT16)0xFFFF)
#define FLASH_TO_IAP_VALUE               ((UINT16)0x00AB)
#define FLASH_TO_APP_VALUE               ((UINT16)0xFFFF)
#define FLASH_UPGRADE_PARAM_FLAG_RESET   ((UINT16)0xFFFF)
#define FLASH_NORMAL_SLEEP_VALUE         ((UINT16)0x1234)
#define FLASH_DEEP_SLEEP_VALUE           ((UINT16)0x1235)
#define FLASH_HICCUP_SLEEP_VALUE         ((UINT16)0x1236)
#define FLASH_SLEEP_CHARGER_WAKE_VALUE   ((UINT16)0x1237)
#define FLASH_SLEEP_RESET_VALUE          ((UINT16)0xFFFF)
#define BOOT_FLAG_RESET_VALUE            FLASH_SLEEP_RESET_VALUE
#define STORAGE_FLASH_SOC_API_DECLARED   1

typedef struct
{
	UINT16 u16FormatVersion;
	UINT16 u16SocNow;
	UINT16 u16DsgSocInt;
	UINT16 u16MaxErrorPercent;
	UINT32 u32CycleTimes;
	UINT32 u32CapNow;
	UINT32 u32CapFull;
	UINT32 u32LearnPassedAs10;
	UINT16 u16LearnAnchorSoc;
	UINT16 u16LearnState;
	UINT16 u16Flags;
	UINT16 u16Reserved[4];
} STORAGE_FLASH_SOC_DATA;

typedef struct
{
	UINT16 protect[FLASH_STORAGE_RW_PARAM_PROTECT_WORD_COUNT];
	UINT16 other[FLASH_STORAGE_RW_PARAM_OTHER_WORD_COUNT];
	UINT16 reserved[FLASH_STORAGE_RW_PARAM_RESERVED_WORD_COUNT];
} STORAGE_FLASH_RW_PARAM_DATA;

typedef struct
{
	UINT16 u16FormatVersion;
	UINT16 u16AppliedPolicyVersion;
	UINT16 afe[FLASH_STORAGE_AFE_WORD_COUNT];
	UINT16 protect[FLASH_STORAGE_RW_PARAM_PROTECT_WORD_COUNT];
	UINT16 other[FLASH_STORAGE_RW_PARAM_OTHER_WORD_COUNT];
	UINT16 reserved[FLASH_STORAGE_RW_PARAM_RESERVED_WORD_COUNT];
} STORAGE_FLASH_CONFIG_DATA;

FLASH_Status FlashWriteOneHalfWord(uint32_t StartAddr, uint16_t Buffer);
UINT16 FlashReadOneHalfWord(UINT32 faddr);
UINT8 AppUpgrade_RequestIap(void);
UINT8 StorageFlash_LoadSocData(STORAGE_FLASH_SOC_DATA *data);
UINT8 StorageFlash_SaveSocData(const STORAGE_FLASH_SOC_DATA *data);
UINT8 StorageFlash_LoadAfeData(UINT16 *values, UINT16 word_count);
UINT8 StorageFlash_SaveAfeData(const UINT16 *values, UINT16 word_count);
UINT8 StorageFlash_LoadRwParamData(STORAGE_FLASH_RW_PARAM_DATA *data);
UINT8 StorageFlash_SaveRwParamData(const STORAGE_FLASH_RW_PARAM_DATA *data);
UINT16 StorageFlash_GetConfigPolicyVersion(void);
UINT8 StorageFlash_SetConfigPolicyVersion(UINT16 version);
UINT8 StorageFlash_LoadLogData(UINT8 *point, UINT8 records[FLASH_STORAGE_LOG_RECORD_COUNT][2]);
UINT8 StorageFlash_SaveLogData(UINT8 point, const UINT8 records[FLASH_STORAGE_LOG_RECORD_COUNT][2]);
UINT8 StorageFlash_IsBusy(void);
void StorageFlash_PrintBootCheck(void);
void App_FlashUpdate(void);
void APP_To_IAP_Jump(void);
void InitAreaSelect(void);

#endif
