#ifndef PROJECT_FEATURES_H
#define PROJECT_FEATURES_H

#include "Project_Config.h"
#include "Project_Protection.h"

#ifndef PROJECT_CFG_FEATURE_AFE
#define PROJECT_CFG_FEATURE_AFE 1
#endif

#ifndef PROJECT_CFG_FEATURE_SOC
#define PROJECT_CFG_FEATURE_SOC 1
#endif

#ifndef PROJECT_CFG_FEATURE_ANALOG_ADC
#define PROJECT_CFG_FEATURE_ANALOG_ADC 1
#endif

#ifndef PROJECT_CFG_FEATURE_RS485
#define PROJECT_CFG_FEATURE_RS485 1
#endif

#ifndef PROJECT_CFG_FEATURE_CAN
#define PROJECT_CFG_FEATURE_CAN 1
#endif

#ifndef PROJECT_CFG_FEATURE_LEDBAR
#define PROJECT_CFG_FEATURE_LEDBAR 1
#endif

#ifndef PROJECT_CFG_FEATURE_STORAGE
#define PROJECT_CFG_FEATURE_STORAGE 1
#endif

#ifndef PROJECT_CFG_FEATURE_LOG_RECORD
#define PROJECT_CFG_FEATURE_LOG_RECORD 1
#endif

#ifndef PROJECT_CFG_FEATURE_PRODUCTION_ID
#define PROJECT_CFG_FEATURE_PRODUCTION_ID 1
#endif

#define PROJECT_FEATURE_WATCHDOG      PROJECT_CFG_WDOG_ENABLE
#define PROJECT_FEATURE_RTC_LOW_POWER PROJECT_CFG_RTC_ENABLE
#define PROJECT_FEATURE_HEAT          PROJECT_CFG_HEAT_ENABLE
#define PROJECT_FEATURE_FACTORY_AGING PROJECT_CFG_FACTORY_AGING_ENABLE

#define PROJECT_FEATURE_AFE           PROJECT_CFG_FEATURE_AFE
#define PROJECT_FEATURE_AFE_HARDWARE_PROTECTION PROJECT_PROTECTION_USES_AFE_HARDWARE
#define PROJECT_FEATURE_SOFTWARE_PROTECTION PROJECT_PROTECTION_USES_MCU_SOFTWARE
#define PROJECT_FEATURE_SOC           PROJECT_CFG_FEATURE_SOC
#define PROJECT_FEATURE_ANALOG_ADC    PROJECT_CFG_FEATURE_ANALOG_ADC
#define PROJECT_FEATURE_RS485         PROJECT_CFG_FEATURE_RS485
#define PROJECT_FEATURE_CAN           PROJECT_CFG_FEATURE_CAN
#define PROJECT_FEATURE_LEDBAR        PROJECT_CFG_FEATURE_LEDBAR
#define PROJECT_FEATURE_STORAGE       PROJECT_CFG_FEATURE_STORAGE
#define PROJECT_FEATURE_LOG_RECORD    PROJECT_CFG_FEATURE_LOG_RECORD
#define PROJECT_FEATURE_PRODUCTION_ID PROJECT_CFG_FEATURE_PRODUCTION_ID

#endif
