#ifndef PROJECT_PROTECTION_H
#define PROJECT_PROTECTION_H

#include "Project_Config.h"

#define PROJECT_PROTECTION_MODE_AFE_HARDWARE_ONLY 0
#define PROJECT_PROTECTION_MODE_MCU_SOFTWARE      1
#define PROJECT_PROTECTION_MODE_HYBRID            2

#ifndef PROJECT_CFG_PROTECTION_MODE
#define PROJECT_CFG_PROTECTION_MODE PROJECT_PROTECTION_MODE_AFE_HARDWARE_ONLY
#endif

#if (PROJECT_CFG_PROTECTION_MODE == PROJECT_PROTECTION_MODE_AFE_HARDWARE_ONLY)
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 1
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 0
#elif (PROJECT_CFG_PROTECTION_MODE == PROJECT_PROTECTION_MODE_MCU_SOFTWARE)
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 0
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 1
#elif (PROJECT_CFG_PROTECTION_MODE == PROJECT_PROTECTION_MODE_HYBRID)
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 1
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 1
#else
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 1
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 0
#endif

#endif
