#ifndef UPGRADE_PARAM_POLICY_H
#define UPGRADE_PARAM_POLICY_H

#include "Project_Config.h"

/*
 * Customer upgrade parameter policy.
 *
 * Workflow for a customer-specific package:
 * 1. Modify the firmware default parameter tables.
 * 2. Open conf/Project_Config.h with Keil Configuration Wizard.
 * 3. Enable only the reset switches that must overwrite field parameters.
 * 4. Increase PROJECT_CFG_UPGRADE_PARAM_POLICY_VERSION before building.
 */
#define UPGRADE_PARAM_POLICY_ENABLE        PROJECT_CFG_UPGRADE_PARAM_POLICY_ENABLE
#define UPGRADE_PARAM_POLICY_VERSION       PROJECT_CFG_UPGRADE_PARAM_POLICY_VERSION

#define UPGRADE_PARAM_RESET_AFE            PROJECT_CFG_UPGRADE_PARAM_RESET_AFE
#define UPGRADE_PARAM_RESET_PROTECT        PROJECT_CFG_UPGRADE_PARAM_RESET_PROTECT
#define UPGRADE_PARAM_RESET_BALANCE_OPEN_VOLTAGE \
	PROJECT_CFG_UPGRADE_PARAM_RESET_BALANCE_OPEN_VOLTAGE
#define UPGRADE_PARAM_RESET_SOC_TABLE      PROJECT_CFG_UPGRADE_PARAM_RESET_SOC_TABLE
#define UPGRADE_PARAM_RESET_SOC_CONFIG     PROJECT_CFG_UPGRADE_PARAM_RESET_SOC_CONFIG
#define UPGRADE_PARAM_RESET_SOC_SNAPSHOT   PROJECT_CFG_UPGRADE_PARAM_RESET_SOC_SNAPSHOT
#define UPGRADE_PARAM_RESET_EVENT_RECORD   PROJECT_CFG_UPGRADE_PARAM_RESET_EVENT_RECORD

/* Test only. Keep 0 in release packages to avoid repeated resets. */
#define UPGRADE_PARAM_FORCE_REAPPLY        PROJECT_CFG_UPGRADE_PARAM_FORCE_REAPPLY

#define UPGRADE_PARAM_POLICY_HAS_ACTION \
	(UPGRADE_PARAM_RESET_AFE || \
	 UPGRADE_PARAM_RESET_PROTECT || \
	 UPGRADE_PARAM_RESET_BALANCE_OPEN_VOLTAGE || \
	 UPGRADE_PARAM_RESET_SOC_TABLE || \
	 UPGRADE_PARAM_RESET_SOC_CONFIG || \
	 UPGRADE_PARAM_RESET_SOC_SNAPSHOT || \
	 UPGRADE_PARAM_RESET_EVENT_RECORD)

#if UPGRADE_PARAM_POLICY_ENABLE && (UPGRADE_PARAM_POLICY_VERSION == 0xFFFF)
#error "UPGRADE_PARAM_POLICY_VERSION must not be 0xFFFF"
#endif

#endif
