#ifndef UPGRADE_PARAM_POLICY_H
#define UPGRADE_PARAM_POLICY_H

#include "Project_Config.h"

#if defined(PROJECT_CFG_UPGRADE_PARAM_POLICY_ENABLE) && (PROJECT_CFG_UPGRADE_PARAM_POLICY_ENABLE != 1)
#error "Upgrade parameter policy is a required board feature and must not be disabled"
#endif

/*
 * Customer upgrade parameter policy.
 *
 * Workflow for a customer-specific package:
 * 1. Modify the firmware default parameter tables.
 * 2. Open conf/Project_Config.h with Keil Configuration Wizard.
 * 3. Enable only the reset actions that must overwrite field parameters.
 * 4. Increase PROJECT_CFG_UPGRADE_PARAM_POLICY_VERSION before building.
 */
#define UPGRADE_PARAM_POLICY_ENABLE        1
#define UPGRADE_PARAM_POLICY_VERSION       PROJECT_CFG_UPGRADE_PARAM_POLICY_VERSION

#define UPGRADE_PARAM_RESET_AFE            PROJECT_CFG_UPGRADE_PARAM_RESET_AFE
#define UPGRADE_PARAM_RESET_PROTECT        PROJECT_CFG_UPGRADE_PARAM_RESET_PROTECT
#define UPGRADE_PARAM_RESET_BALANCE_OPEN_VOLTAGE \
	PROJECT_CFG_UPGRADE_PARAM_RESET_BALANCE_OPEN_VOLTAGE
#define UPGRADE_PARAM_RESET_SOC_CONFIG     PROJECT_CFG_UPGRADE_PARAM_RESET_SOC_CONFIG
#define UPGRADE_PARAM_RESET_SOC_SNAPSHOT   PROJECT_CFG_UPGRADE_PARAM_RESET_SOC_SNAPSHOT
#define UPGRADE_PARAM_RESET_EVENT_RECORD   PROJECT_CFG_UPGRADE_PARAM_RESET_EVENT_RECORD
#define UPGRADE_PARAM_RESET_FACTORY_AGING_TIME \
	PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME
#define UPGRADE_PARAM_UPDATE_OTHER_ELEMENT \
	PROJECT_CFG_UPGRADE_PARAM_UPDATE_OTHER_ELEMENT

#define UPGRADE_PARAM_OTHER_ELEMENT_CONFIG { \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_OPEN_VOLTAGE, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_OPEN_WINDOW, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_CLOSE_WINDOW, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_RES1, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_RES2, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_RES3, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_RES4, \
	PROJECT_CFG_UPGRADE_OTHER_BALANCE_RES5, \
	PROJECT_CFG_UPGRADE_OTHER_CS_CUR_CHGMAX, \
	PROJECT_CFG_UPGRADE_OTHER_CS_CUR_DSGMAX, \
	PROJECT_CFG_UPGRADE_OTHER_CBC_DELAY_T, \
	PROJECT_CFG_UPGRADE_OTHER_CBC_CUR_DSG, \
	PROJECT_CFG_UPGRADE_OTHER_SOC_TABLE_SELECT, \
	PROJECT_CFG_UPGRADE_OTHER_PASSWORD_ALWAYS, \
	PROJECT_CFG_UPGRADE_OTHER_CUR_LIMIT_VDELTA, \
	PROJECT_CFG_UPGRADE_OTHER_CUR_LIMIT_CUR, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_V_NORMAL, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_TIME_NORMAL, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_V_LOW, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_TIME_LOW, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_VIR_CUR_CHG, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_VIR_CUR_DSG, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_RTC_WAKEUP_TIME, \
	PROJECT_CFG_UPGRADE_OTHER_SLEEP_TIME_RTC, \
	PROJECT_CFG_UPGRADE_OTHER_SOC_AH, \
	PROJECT_CFG_UPGRADE_OTHER_SOC_CYCLE_TIMES, \
	PROJECT_CFG_UPGRADE_OTHER_SOC_V_100, \
	PROJECT_CFG_UPGRADE_OTHER_SOC_V_0, \
	PROJECT_CFG_UPGRADE_OTHER_SYS_SERIES_NUM, \
	PROJECT_CFG_UPGRADE_OTHER_SYS_CS_RES, \
	PROJECT_CFG_UPGRADE_OTHER_SYS_CS_RES_NUM, \
	PROJECT_CFG_UPGRADE_OTHER_SYS_PRECHG_TIME \
}

/* Test only. Keep fixed 0 in release packages to avoid repeated resets. */
#define UPGRADE_PARAM_FORCE_REAPPLY        0

#define UPGRADE_PARAM_POLICY_HAS_ACTION \
	(UPGRADE_PARAM_RESET_AFE || \
	 UPGRADE_PARAM_RESET_PROTECT || \
	 UPGRADE_PARAM_RESET_BALANCE_OPEN_VOLTAGE || \
	 UPGRADE_PARAM_RESET_SOC_CONFIG || \
	 UPGRADE_PARAM_RESET_SOC_SNAPSHOT || \
	 UPGRADE_PARAM_RESET_EVENT_RECORD || \
	 UPGRADE_PARAM_RESET_FACTORY_AGING_TIME || \
	 UPGRADE_PARAM_UPDATE_OTHER_ELEMENT)

#if UPGRADE_PARAM_POLICY_ENABLE && (UPGRADE_PARAM_POLICY_VERSION == 0xFFFF)
#error "UPGRADE_PARAM_POLICY_VERSION must not be 0xFFFF"
#endif

#endif
