#ifndef PROJECT_BUILD_GUARD_H
#define PROJECT_BUILD_GUARD_H

#include "Project_Config.h"

#ifndef PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA
#define PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA 30
#endif

#ifndef PROJECT_CFG_HOST_WRITE_ENABLE
#define PROJECT_CFG_HOST_WRITE_ENABLE 1
#endif

#ifndef PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC
#define PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC 3600
#endif

#endif

/* --- range checks --- */

#if (PROJECT_CFG_BAT_CHEMISTRY != 0) && (PROJECT_CFG_BAT_CHEMISTRY != 1)
#error "Invalid PROJECT_CFG_BAT_CHEMISTRY"
#endif

#if (PROJECT_CFG_HOST_WRITE_ENABLE != 0) && (PROJECT_CFG_HOST_WRITE_ENABLE != 1)
#error "Invalid PROJECT_CFG_HOST_WRITE_ENABLE"
#endif

/* SOC checks */
#if (PROJECT_CFG_SOC_FULL_CONFIRM_MIN_CELL_MARGIN_MV > 500)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_MIN_CELL_MARGIN_MV"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_MAX_CELL_DELTA_MV > 1000)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_MAX_CELL_DELTA_MV"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS < 1) || (PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS > 600)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_FAST_SECONDS < 1) || (PROJECT_CFG_SOC_FULL_CONFIRM_FAST_SECONDS > 600)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_FAST_SECONDS"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_FAST_SECONDS > PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS)
#error "SOC full fast confirm time must not exceed normal confirm time"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_MIN_SOC_PERCENT > 100)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_MIN_SOC_PERCENT"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_FAST_MARGIN_MV > 500)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_FAST_MARGIN_MV"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV < 1000) || (PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV > 3500)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV < 3600) || (PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV > 6000)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV >= PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV)
#error "SOC calibration min voltage must be less than max voltage"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_DELTA_MV > 3000)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_DELTA_MV"
#endif
#if (PROJECT_CFG_SOC_SAG_HOLDOFF_SECONDS > 1800)
#error "Invalid PROJECT_CFG_SOC_SAG_HOLDOFF_SECONDS"
#endif
#if (PROJECT_CFG_SOC_SAG_ALLOW_OFFSET_MV > 500)
#error "Invalid PROJECT_CFG_SOC_SAG_ALLOW_OFFSET_MV"
#endif
#if (PROJECT_CFG_SOC_REST_OCV_SECONDS < 60) || (PROJECT_CFG_SOC_REST_OCV_SECONDS > 43200)
#error "Invalid PROJECT_CFG_SOC_REST_OCV_SECONDS"
#endif
#if (PROJECT_CFG_SOC_REST_DOWN_STEP_SECONDS < 60) || (PROJECT_CFG_SOC_REST_DOWN_STEP_SECONDS > 43200)
#error "Invalid PROJECT_CFG_SOC_REST_DOWN_STEP_SECONDS"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_STEP_PERCENT < 1) || (PROJECT_CFG_SOC_CALIBRATION_STEP_PERCENT > 10)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_STEP_PERCENT"
#endif
#if (PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA > 1000)
#error "Invalid PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA"
#endif
#if (PROJECT_CFG_SOC_EMPTY_TAIL_START_OFFSET_MV > 1000)
#error "Invalid PROJECT_CFG_SOC_EMPTY_TAIL_START_OFFSET_MV"
#endif
#if (PROJECT_CFG_SOC_DISPLAY_NORMAL_SECONDS < 1) || (PROJECT_CFG_SOC_DISPLAY_NORMAL_SECONDS > 60)
#error "Invalid PROJECT_CFG_SOC_DISPLAY_NORMAL_SECONDS"
#endif
#if (PROJECT_CFG_SOC_DISPLAY_CHG_SECONDS < 1) || (PROJECT_CFG_SOC_DISPLAY_CHG_SECONDS > 60)
#error "Invalid PROJECT_CFG_SOC_DISPLAY_CHG_SECONDS"
#endif
#if (PROJECT_CFG_SOC_DISPLAY_LOW_SECONDS < 1) || (PROJECT_CFG_SOC_DISPLAY_LOW_SECONDS > 60)
#error "Invalid PROJECT_CFG_SOC_DISPLAY_LOW_SECONDS"
#endif
#if (PROJECT_CFG_SOC_DISPLAY_LOW_OFFSET_MV > 500)
#error "Invalid PROJECT_CFG_SOC_DISPLAY_LOW_OFFSET_MV"
#endif
#if (PROJECT_CFG_SOC_DISPLAY_EMPTY_FAST_BELOW_V0_MV > 500)
#error "Invalid PROJECT_CFG_SOC_DISPLAY_EMPTY_FAST_BELOW_V0_MV"
#endif

/* factory aging */
#if (PROJECT_CFG_FACTORY_AGING_ENABLE != 0) && (PROJECT_CFG_FACTORY_AGING_ENABLE != 1)
#error "Invalid PROJECT_CFG_FACTORY_AGING_ENABLE"
#endif
#if (PROJECT_CFG_FACTORY_AGING_DURATION_SECONDS < 1) || (PROJECT_CFG_FACTORY_AGING_DURATION_SECONDS > 604800)
#error "Invalid PROJECT_CFG_FACTORY_AGING_DURATION_SECONDS"
#endif
#if (PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME != 0) && (PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME != 1)
#error "Invalid PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME"
#endif
#if PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME && !PROJECT_CFG_FACTORY_AGING_ENABLE
#error "PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME requires PROJECT_CFG_FACTORY_AGING_ENABLE"
#endif

/* log */
#if (PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC > 86400)
#error "Invalid PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC"
#endif
