#ifndef PROJECT_BUILD_GUARD_H
#define PROJECT_BUILD_GUARD_H

#include "Project_Config.h"

#ifndef PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA
#define PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA 30
#endif

#ifndef PROJECT_CFG_HOST_WRITE_ENABLE
#define PROJECT_CFG_HOST_WRITE_ENABLE 1
#endif

#ifndef PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC
#define PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC 3600
#endif

#ifndef PROJECT_CFG_RUNTIME_LOG_ENABLE
#define PROJECT_CFG_RUNTIME_LOG_ENABLE 0
#endif

#ifndef PROJECT_CFG_RUNTIME_LOG_LEVEL
#define PROJECT_CFG_RUNTIME_LOG_LEVEL 3
#endif

#ifndef PROJECT_CFG_RUNTIME_LOG_HEARTBEAT_SECONDS
#define PROJECT_CFG_RUNTIME_LOG_HEARTBEAT_SECONDS 1
#endif

#ifndef PROJECT_CFG_RUNTIME_LOG_UART
#define PROJECT_CFG_RUNTIME_LOG_UART 1
#endif

#ifndef PROJECT_CFG_BUILD_PROFILE
#define PROJECT_CFG_BUILD_PROFILE 0
#endif

#ifndef PROJECT_CFG_DEBUG_WATCH_ENABLE
#define PROJECT_CFG_DEBUG_WATCH_ENABLE 0
#endif

#ifndef PROJECT_CFG_DEBUG_MONITOR_ENABLE
#define PROJECT_CFG_DEBUG_MONITOR_ENABLE 0
#endif

#ifndef PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE
#define PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE 0
#endif

#ifndef PROJECT_CFG_IRQ_DEBUG_ENABLE
#define PROJECT_CFG_IRQ_DEBUG_ENABLE 0
#endif

#ifndef PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE
#define PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE 0
#endif

#if defined(PROJECT_CFG_IAP_ENABLE) && (PROJECT_CFG_IAP_ENABLE != 1)
#error "IAP is a required board feature and must not be disabled"
#endif

#if defined(PROJECT_CFG_UPGRADE_PARAM_POLICY_ENABLE) && (PROJECT_CFG_UPGRADE_PARAM_POLICY_ENABLE != 1)
#error "Upgrade parameter policy is a required board feature and must not be disabled"
#endif

#if defined(PROJECT_CFG_FACTORY_AGING_ENABLE) && (PROJECT_CFG_FACTORY_AGING_ENABLE != 1)
#error "Factory aging is a required board feature and must not be disabled"
#endif

#endif

/* --- range checks --- */

#if (PROJECT_CFG_BUILD_PROFILE != 0) && (PROJECT_CFG_BUILD_PROFILE != 1) && (PROJECT_CFG_BUILD_PROFILE != 2)
#error "Invalid PROJECT_CFG_BUILD_PROFILE"
#endif

#if (PROJECT_CFG_BAT_CHEMISTRY != 0) && (PROJECT_CFG_BAT_CHEMISTRY != 1)
#error "Invalid PROJECT_CFG_BAT_CHEMISTRY"
#endif

#if (PROJECT_CFG_HOST_WRITE_ENABLE != 0) && (PROJECT_CFG_HOST_WRITE_ENABLE != 1)
#error "Invalid PROJECT_CFG_HOST_WRITE_ENABLE"
#endif

#if (PROJECT_CFG_DEBUG_WATCH_ENABLE != 0) && (PROJECT_CFG_DEBUG_WATCH_ENABLE != 1)
#error "Invalid PROJECT_CFG_DEBUG_WATCH_ENABLE"
#endif

#if (PROJECT_CFG_DEBUG_MONITOR_ENABLE != 0) && (PROJECT_CFG_DEBUG_MONITOR_ENABLE != 1)
#error "Invalid PROJECT_CFG_DEBUG_MONITOR_ENABLE"
#endif

#if (PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE != 0) && (PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE != 1)
#error "Invalid PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE"
#endif

#if (PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE != 0) && (PROJECT_CFG_DEBUG_MONITOR_ENABLE == 0)
#error "PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE requires PROJECT_CFG_DEBUG_MONITOR_ENABLE"
#endif

#if (PROJECT_CFG_IRQ_DEBUG_ENABLE != 0) && (PROJECT_CFG_IRQ_DEBUG_ENABLE != 1)
#error "Invalid PROJECT_CFG_IRQ_DEBUG_ENABLE"
#endif

#if (PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE != 0) && (PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE != 1)
#error "Invalid PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE"
#endif

#if (PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE != 0) && (PROJECT_CFG_IRQ_DEBUG_ENABLE == 0)
#error "PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE requires PROJECT_CFG_IRQ_DEBUG_ENABLE"
#endif

#if (PROJECT_CFG_BUILD_PROFILE == 0) && \
	((PROJECT_CFG_DEBUG_WATCH_ENABLE != 0) || \
	 (PROJECT_CFG_DEBUG_MONITOR_ENABLE != 0) || \
	 (PROJECT_CFG_DEBUG_HUB_AUTORUN_ENABLE != 0) || \
	 (PROJECT_CFG_RUNTIME_LOG_ENABLE != 0) || \
	 (PROJECT_CFG_IRQ_DEBUG_ENABLE != 0) || \
	 (PROJECT_CFG_IRQ_DEBUG_EVENT_ENABLE != 0))
#error "Debug watch, system debug, runtime log and IRQ debug must stay disabled for release build profile"
#endif

/* SOC checks */
#if (PROJECT_CFG_SOC_FULL_CONFIRM_MIN_CELL_MARGIN_MV > 500)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_MIN_CELL_MARGIN_MV"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_MAX_CELL_DELTA_MV > 1000)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_MAX_CELL_DELTA_MV"
#endif
#if (PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS < 1) || (PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS > 600)
#error "Invalid PROJECT_CFG_SOC_FULL_CONFIRM_SECONDS"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV < 1000) || (PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV > 3500)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV < 3600) || (PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV > 6000)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV >= PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV)
#error "SOC calibration min voltage must be less than max voltage"
#endif
#if (PROJECT_CFG_SOC_SAG_HOLDOFF_SECONDS > 1800)
#error "Invalid PROJECT_CFG_SOC_SAG_HOLDOFF_SECONDS"
#endif
#if (PROJECT_CFG_SOC_SAG_ALLOW_OFFSET_MV > 500)
#error "Invalid PROJECT_CFG_SOC_SAG_ALLOW_OFFSET_MV"
#endif
#if (PROJECT_CFG_SOC_REST_OCV_SECONDS < 60) || (PROJECT_CFG_SOC_REST_OCV_SECONDS > 43200)
#error "Invalid PROJECT_CFG_SOC_REST_OCV_SECONDS"
#endif
#if (PROJECT_CFG_SOC_REST_DOWN_STEP_SECONDS < 60) || (PROJECT_CFG_SOC_REST_DOWN_STEP_SECONDS > 43200)
#error "Invalid PROJECT_CFG_SOC_REST_DOWN_STEP_SECONDS"
#endif
#if (PROJECT_CFG_SOC_CALIBRATION_STEP_PERCENT < 1) || (PROJECT_CFG_SOC_CALIBRATION_STEP_PERCENT > 10)
#error "Invalid PROJECT_CFG_SOC_CALIBRATION_STEP_PERCENT"
#endif
#if (PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA > 1000)
#error "Invalid PROJECT_CFG_SOC_BOARD_SELF_CONSUMPTION_MA"
#endif
#if (PROJECT_CFG_SOC_EMPTY_TAIL_START_OFFSET_MV > 1000)
#error "Invalid PROJECT_CFG_SOC_EMPTY_TAIL_START_OFFSET_MV"
#endif

/* factory aging */
#if (PROJECT_CFG_FACTORY_AGING_DURATION_SECONDS < 1) || (PROJECT_CFG_FACTORY_AGING_DURATION_SECONDS > 604800)
#error "Invalid PROJECT_CFG_FACTORY_AGING_DURATION_SECONDS"
#endif
#if (PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME != 0) && (PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME != 1)
#error "Invalid PROJECT_CFG_UPGRADE_PARAM_RESET_FACTORY_AGING_TIME"
#endif

/* log */
#if (PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC > 86400)
#error "Invalid PROJECT_CFG_LOG_RECORD_REPEAT_MIN_INTERVAL_SEC"
#endif
#if (PROJECT_CFG_RUNTIME_LOG_ENABLE != 0) && (PROJECT_CFG_RUNTIME_LOG_ENABLE != 1)
#error "Invalid PROJECT_CFG_RUNTIME_LOG_ENABLE"
#endif
#if (PROJECT_CFG_RUNTIME_LOG_LEVEL < 1) || (PROJECT_CFG_RUNTIME_LOG_LEVEL > 5)
#error "Invalid PROJECT_CFG_RUNTIME_LOG_LEVEL"
#endif
#if (PROJECT_CFG_RUNTIME_LOG_HEARTBEAT_SECONDS < 1) || (PROJECT_CFG_RUNTIME_LOG_HEARTBEAT_SECONDS > 60)
#error "Invalid PROJECT_CFG_RUNTIME_LOG_HEARTBEAT_SECONDS"
#endif
#if (PROJECT_CFG_RUNTIME_LOG_UART < 1) || (PROJECT_CFG_RUNTIME_LOG_UART > 3)
#error "Invalid PROJECT_CFG_RUNTIME_LOG_UART"
#endif
