#ifndef PROJECT_ADVANCED_CONFIG_H
#define PROJECT_ADVANCED_CONFIG_H

/*
 * Internal defaults for test switches and tuning knobs.
 *
 * Do not expose these in the daily Keil Configuration Wizard surface. If a
 * special validation build must change one item, prefer a Keil target define
 * or edit this file intentionally with a clear test/release note.
 */

/* Debug and destructive test defaults. */
#ifndef PROJECT_CFG_DEBUG_CODE_ENABLE
#define PROJECT_CFG_DEBUG_CODE_ENABLE 0
#endif

#ifndef PROJECT_CFG_EBIKE_RIDE_SIM_ENABLE
#define PROJECT_CFG_EBIKE_RIDE_SIM_ENABLE 0
#endif

#ifndef PROJECT_CFG_EBIKE_RIDE_SIM_PROFILE
#define PROJECT_CFG_EBIKE_RIDE_SIM_PROFILE 0
#endif

#ifndef PROJECT_CFG_EBIKE_RIDE_SIM_INITIAL_SOC_PERCENT
#define PROJECT_CFG_EBIKE_RIDE_SIM_INITIAL_SOC_PERCENT 80
#endif

#ifndef PROJECT_CFG_EBIKE_RIDE_SIM_CELL_RES_MOHM
#define PROJECT_CFG_EBIKE_RIDE_SIM_CELL_RES_MOHM 8
#endif

#ifndef PROJECT_CFG_EBIKE_RIDE_SIM_CELL_IMBALANCE_MV
#define PROJECT_CFG_EBIKE_RIDE_SIM_CELL_IMBALANCE_MV 6
#endif

#ifndef PROJECT_CFG_SOC_AUTO_TEST_ENABLE
#define PROJECT_CFG_SOC_AUTO_TEST_ENABLE 0
#endif

#ifndef PROJECT_CFG_SOC_AUTO_TEST_TICKS_PER_CALL
#define PROJECT_CFG_SOC_AUTO_TEST_TICKS_PER_CALL 100
#endif

#ifndef PROJECT_CFG_FLASH64K_QUICK_TEST_ENABLE
#define PROJECT_CFG_FLASH64K_QUICK_TEST_ENABLE 0
#endif

#ifndef PROJECT_CFG_FLASH64K_QUICK_TEST_CYCLES
#define PROJECT_CFG_FLASH64K_QUICK_TEST_CYCLES 96
#endif

#ifndef PROJECT_CFG_FLASH64K_USE_TEST_ENABLE
#define PROJECT_CFG_FLASH64K_USE_TEST_ENABLE 0
#endif

#ifndef PROJECT_CFG_FLASH64K_USE_TEST_PRINT_PERIOD_SEC
#define PROJECT_CFG_FLASH64K_USE_TEST_PRINT_PERIOD_SEC 10
#endif

#ifndef PROJECT_CFG_FLASH64K_USE_TEST_ACCEL_ENABLE
#define PROJECT_CFG_FLASH64K_USE_TEST_ACCEL_ENABLE 0
#endif

#ifndef PROJECT_CFG_FLASH64K_USE_TEST_ACCEL_SOC_PERIOD_SEC
#define PROJECT_CFG_FLASH64K_USE_TEST_ACCEL_SOC_PERIOD_SEC 1
#endif

#ifndef PROJECT_CFG_FLASH64K_USE_TEST_ACCEL_AFE_PERIOD_SEC
#define PROJECT_CFG_FLASH64K_USE_TEST_ACCEL_AFE_PERIOD_SEC 30
#endif

/* SOC algorithm tuning defaults. */
#ifndef PROJECT_CFG_SOC_FULL_CONFIRM_MIN_CELL_MARGIN_MV
#define PROJECT_CFG_SOC_FULL_CONFIRM_MIN_CELL_MARGIN_MV 80
#endif

#ifndef PROJECT_CFG_SOC_FULL_CONFIRM_MAX_CELL_DELTA_MV
#define PROJECT_CFG_SOC_FULL_CONFIRM_MAX_CELL_DELTA_MV 120
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_GUARD_ENABLE
#define PROJECT_CFG_SOC_ONLINE_OCV_GUARD_ENABLE 1
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_CORRECTION_SECONDS
#define PROJECT_CFG_SOC_ONLINE_OCV_CORRECTION_SECONDS 30
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_MIN_DELTA_PERCENT
#define PROJECT_CFG_SOC_ONLINE_OCV_MIN_DELTA_PERCENT 3
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_CURRENT_DIVIDER
#define PROJECT_CFG_SOC_ONLINE_OCV_CURRENT_DIVIDER 10
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_HEAVY_DSG_CURRENT_DIVIDER
#define PROJECT_CFG_SOC_ONLINE_OCV_HEAVY_DSG_CURRENT_DIVIDER 3
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_HEAVY_DSG_HOLDOFF_SECONDS
#define PROJECT_CFG_SOC_ONLINE_OCV_HEAVY_DSG_HOLDOFF_SECONDS 180
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_STABLE_SECONDS
#define PROJECT_CFG_SOC_ONLINE_OCV_STABLE_SECONDS 20
#endif

#ifndef PROJECT_CFG_SOC_ONLINE_OCV_STABLE_WINDOW_MV
#define PROJECT_CFG_SOC_ONLINE_OCV_STABLE_WINDOW_MV 8
#endif

#ifndef PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV
#define PROJECT_CFG_SOC_CALIBRATION_MIN_CELL_VALID_MV 2000
#endif

#ifndef PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV
#define PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_VALID_MV 5000
#endif

#ifndef PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_DELTA_MV
#define PROJECT_CFG_SOC_CALIBRATION_MAX_CELL_DELTA_MV 300
#endif

#ifndef PROJECT_CFG_SOC_CALIBRATION_BLOCK_PROTECTION_FAULT
#define PROJECT_CFG_SOC_CALIBRATION_BLOCK_PROTECTION_FAULT 0
#endif

#ifndef PROJECT_CFG_SOC_CALIBRATION_BLOCK_SYSTEM_FAULT
#define PROJECT_CFG_SOC_CALIBRATION_BLOCK_SYSTEM_FAULT 0
#endif

/* LedBar timing and validation defaults. */
#ifndef PROJECT_CFG_LEDBAR_LONG_PRESS_GPIO_TOGGLE_TEST
#define PROJECT_CFG_LEDBAR_LONG_PRESS_GPIO_TOGGLE_TEST 0
#endif

#ifndef PROJECT_CFG_LEDBAR_SOC_DISPLAY_10MS
#define PROJECT_CFG_LEDBAR_SOC_DISPLAY_10MS 500
#endif

#ifndef PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_ENABLE
#define PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_ENABLE 0
#endif

#ifndef PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_WINDOW
#define PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_WINDOW 2
#endif

#ifndef PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_MIN_EXTRA
#define PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_MIN_EXTRA 4
#endif

#ifndef PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_MIN_GAIN
#define PROJECT_CFG_LEDBAR_SOC_DISPLAY_SNAP_MIN_GAIN 1
#endif

#ifndef PROJECT_CFG_LEDBAR_SCAN_TIMER_100KHZ_TICKS
#define PROJECT_CFG_LEDBAR_SCAN_TIMER_100KHZ_TICKS 50
#endif

#ifndef PROJECT_CFG_LEDBAR_MCU_WK_ON_FILTER_10MS
#define PROJECT_CFG_LEDBAR_MCU_WK_ON_FILTER_10MS 3
#endif

#ifndef PROJECT_CFG_LEDBAR_MCU_WK_OFF_FILTER_10MS
#define PROJECT_CFG_LEDBAR_MCU_WK_OFF_FILTER_10MS 3
#endif

#ifndef PROJECT_CFG_LEDBAR_CHARGE_ON_FILTER_100MS
#define PROJECT_CFG_LEDBAR_CHARGE_ON_FILTER_100MS 1
#endif

#ifndef PROJECT_CFG_LEDBAR_CHARGE_OFF_FILTER_100MS
#define PROJECT_CFG_LEDBAR_CHARGE_OFF_FILTER_100MS 5
#endif

#endif
