#ifndef PROJECT_FEATURES_H
#define PROJECT_FEATURES_H

#include "Project_Protection.h"
#include "Project_Template_Config.h"

#define PROJECT_FEATURE_AFE                 1
#define PROJECT_FEATURE_AFE_HARDWARE_PROTECTION PROJECT_PROTECTION_USES_AFE_HARDWARE
#define PROJECT_FEATURE_SOFTWARE_PROTECTION PROJECT_PROTECTION_USES_MCU_SOFTWARE
#define PROJECT_FEATURE_SOC                 PROJECT_CFG_FEATURE_SOC
#define PROJECT_FEATURE_LOW_POWER           PROJECT_CFG_FEATURE_LOW_POWER
#define PROJECT_FEATURE_RTC                 PROJECT_CFG_FEATURE_RTC
#define PROJECT_FEATURE_RS485               PROJECT_CFG_FEATURE_RS485
#define PROJECT_FEATURE_CAN                 PROJECT_CFG_FEATURE_CAN
#define PROJECT_FEATURE_LEDBAR              PROJECT_CFG_FEATURE_LEDBAR
#define PROJECT_FEATURE_HEAT                PROJECT_CFG_FEATURE_HEAT
#define PROJECT_FEATURE_STORAGE             PROJECT_CFG_STORAGE_INTERNAL_FLASH

#endif /* PROJECT_FEATURES_H */
