#ifndef PROJECT_PROTECTION_H
#define PROJECT_PROTECTION_H

#include "Project_Template_Config.h"

#define PROJECT_PROTECTION_MODE_AFE_HARDWARE_ONLY 0
#define PROJECT_PROTECTION_MODE_MCU_SOFTWARE      1
#define PROJECT_PROTECTION_MODE_HYBRID            2

#if (PROJECT_CFG_PROTECTION_MCU_SOFTWARE && PROJECT_CFG_PROTECTION_AFE_HARDWARE)
#define PROJECT_CFG_PROTECTION_MODE PROJECT_PROTECTION_MODE_HYBRID
#elif PROJECT_CFG_PROTECTION_MCU_SOFTWARE
#define PROJECT_CFG_PROTECTION_MODE PROJECT_PROTECTION_MODE_MCU_SOFTWARE
#elif PROJECT_CFG_PROTECTION_AFE_HARDWARE
#define PROJECT_CFG_PROTECTION_MODE PROJECT_PROTECTION_MODE_AFE_HARDWARE_ONLY
#else
#error "A002 template requires one protection owner"
#endif

#if (PROJECT_CFG_PROTECTION_MODE == PROJECT_PROTECTION_MODE_AFE_HARDWARE_ONLY)
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 1
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 0
#elif (PROJECT_CFG_PROTECTION_MODE == PROJECT_PROTECTION_MODE_MCU_SOFTWARE)
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 0
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 1
#elif (PROJECT_CFG_PROTECTION_MODE == PROJECT_PROTECTION_MODE_HYBRID)
#define PROJECT_PROTECTION_USES_AFE_HARDWARE 1
#define PROJECT_PROTECTION_USES_MCU_SOFTWARE 1
#else
#error "Invalid PROJECT_CFG_PROTECTION_MODE"
#endif

#endif /* PROJECT_PROTECTION_H */
